// Generated by Wrangler by running `wrangler types`

interface Env {
	GUARDIAN_AGENT: DurableObjectNamespace<import("./src/index").GuardianWorker>;
	LEAD_AGENT: DurableObjectNamespace<import("./src/index").LeadWorker>;
	ARM: Fetcher;
}
