// Generated by Wrangler by running `wrangler types`

interface Env {
	CEO_AGENT: DurableObjectNamespace<import("./src/index").CEOWorker>;
	CONTENT_AGENT: DurableObjectNamespace<import("./src/index").ContentWorker>;
	RESEARCHER_AGENT: DurableObjectNamespace<import("./src/index").ResearcherWorker>;
	ARM: Fetcher;
}
