// Generated by Wrangler by running `wrangler types`

interface Env {
	GROWTH_AGENT: DurableObjectNamespace<import("./src/index").GrowthWorker>;
	MARKET_AGENT: DurableObjectNamespace<import("./src/index").MarketWorker>;
	CX_AGENT: DurableObjectNamespace<import("./src/index").CXWorker>;
	SEO_AGENT: DurableObjectNamespace<import("./src/index").SEOWorker>;
	ARM: Fetcher;
}
