// Generated by Wrangler by running `wrangler types`

interface Env {
	GAMER_AGENT: DurableObjectNamespace<import("./src/index").GamerWorker>;
	TRAVEL_AGENT: DurableObjectNamespace<import("./src/index").TravelWorker>;
	CINEMA_AGENT: DurableObjectNamespace<import("./src/index").CinemaWorker>;
	HOBBY_AGENT: DurableObjectNamespace<import("./src/index").HobbyWorker>;
	GACHA_AGENT: DurableObjectNamespace<import("./src/index").GachaWorker>;
	ARM: Fetcher;
}
